import os
import re
import time
import datetime
import subprocess

from state import AgentState
from utils_files.results_saving import save_to_csv, save_to_file
from utils_files.memory import save_negative_experience
from utils_files.file_ops import extract_code
from utils_files.status import Status
from utils_files.coverage import extract_coverage_percent
from config import PROJECT_CONFIG


# =====================================================
# ------ FUNCTION FOR VIVADO EXECUTION ------
# =====================================================
def execute_vivado(bat_file_path: str, working_dir: str):
    start_time = time.time()

    try:
        result = subprocess.run(
            [bat_file_path],
            cwd=working_dir,
            capture_output=True,
            text=True,
            shell=True,
            timeout=300
        )

        raw_output = result.stdout + "\n" + result.stderr
        returncode = result.returncode

    except subprocess.TimeoutExpired:
        print("VIVADO timeout")
        raw_output = "ERROR: Timeout - Vivado simulation or compilation hanged."
        returncode = 1

    end_time = time.time()
    exec_time = round(end_time - start_time, 2)

    return returncode, raw_output, exec_time


# =====================================================
# ------ FUNCTION FOR SAVING CHECKER METRICS ------
# =====================================================
def save_checker_metrics(
    state: AgentState,
    status: Status,
    exec_time: float,
    coverage_val: str,
    error_summary: str,
    raw_errors: str
):
    """
    Save Vivado/checker experimental data in TXT and CSV files.
    This file is separate from agent_metrics.csv.
    """

    results_dir = os.path.join("..", "results")
    os.makedirs(results_dir, exist_ok=True)

    raport_path = os.path.join(results_dir, "raport_experimental.txt")
    csv_path = os.path.join(results_dir, "experimental_metrics_FIFO3.csv")

    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    generated_solutions = state.get("iterations", 0)
    tokens = state.get("iteration_tokens", 0)

    # Save to TXT
    content_txt = (
        f"[{timestamp}] "
        f"GeneratedSolutions: {generated_solutions} | "
        f"Status: {status.value} | "
        f"Coverage: {coverage_val} | "
        f"Vivado_exec_time: {exec_time}s\n"
    )

    if status == Status.FAILED:
        content_txt += f"Errors:\n{raw_errors}\n"

    save_to_file(content_txt, raport_path)

    # Save to CSV
    checker_header = [
        "Timestamp",
        "GeneratedSolutions",
        "Status",
        "Vivado_Execution_sec",
        "Coverage",
        "Error_type",
        "Tokens_Used"
    ]

    content_csv = [
        timestamp,
        generated_solutions,
        status.value,
        exec_time,
        coverage_val,
        error_summary,
        tokens
    ]

    save_to_csv(content_csv, csv_path, header=checker_header)


# =====================================================
# ------ PATH PREPARATION ------
# =====================================================
def prepare_checker_paths():
    bat_file_path = PROJECT_CONFIG["bat_file_path"]
    working_dir = os.path.dirname(bat_file_path)

    return {
        "bat_file_path": bat_file_path,
        "working_dir": working_dir,
        "report_file_path": os.path.join(
            working_dir,
            "coverage_report_text",
            "functionalCoverageReport",
            "xcrg_func_cov_report.txt"
        ),
        "sim_log_path": os.path.join(working_dir, "combined_xsim.log")
    }


# =====================================================
# ------ LOG FILE HANDLING ------
# =====================================================
def is_current_test_log(filename: str) -> bool:
    """
    Accepts only intentional test logs generated by MakeSVfile.bat.
    Rejects Vivado backup logs such as xsim_13564.backup.log.
    """

    return (
        filename.startswith("xsim_test")
        and filename.endswith(".log")
        and ".backup." not in filename
    )


def clean_old_simulation_logs(working_dir: str):
    """
    Removes old xsim test logs before a new Vivado run.
    This prevents the Analyzer from reading stale logs from previous runs.
    """

    try:
        for filename in os.listdir(working_dir):
            if is_current_test_log(filename) or filename == "combined_xsim.log":
                os.remove(os.path.join(working_dir, filename))
            if filename.startswith("xsim") and filename.endswith(".log"):
                os.remove(os.path.join(working_dir, filename))

    except Exception as e:
        print(f"[CHECKER WARNING] Could not clean old simulation logs: {e}")


def build_combined_simulation_log(working_dir: str, raw_output: str = "") -> str:
    """
    Collects Vivado stdout/stderr and all current xsim test logs into one file.
    Backup logs are intentionally ignored.
    """

    combined_log_path = os.path.join(working_dir, "combined_xsim.log")
    log_files = []

    try:
        for filename in os.listdir(working_dir):
            if is_current_test_log(filename):
                log_files.append(filename)

        log_files = sorted(log_files)

        with open(combined_log_path, "w", encoding="utf-8", errors="ignore") as out:
            out.write("===== VIVADO STDOUT / STDERR =====\n")

            if raw_output.strip():
                out.write(raw_output)
            else:
                out.write("[INFO] No Vivado stdout/stderr captured.\n")

            if not log_files:
                out.write("\n\n[WARNING] No xsim_test*.log files found.\n")

                fallback_log = os.path.join(working_dir, "xsim.log")

                if os.path.exists(fallback_log):
                    out.write("\n===== FALLBACK: xsim.log =====\n")
                    with open(fallback_log, "r", encoding="utf-8", errors="ignore") as f:
                        out.write(f.read())
                else:
                    out.write("[WARNING] xsim.log fallback was also not found.\n")

            for log_file in log_files:
                log_path = os.path.join(working_dir, log_file)

                out.write(f"\n\n===== {log_file} =====\n")

                with open(log_path, "r", encoding="utf-8", errors="ignore") as f:
                    out.write(f.read())

    except Exception as e:
        with open(combined_log_path, "w", encoding="utf-8", errors="ignore") as out:
            out.write(f"[ERROR] Failed to build combined simulation log: {e}\n")

    return combined_log_path


# =====================================================
# ------ VIVADO ERROR PARSING ------
# =====================================================
def has_vivado_error(returncode: int, raw_output: str, combined_log: str = "") -> bool:
    """
    Detects only real blocking errors.

    A run is considered failed only when:
    - Vivado/XSim returns a non-zero process code;
    - Vivado reports a real compile/elaboration error;
    - UVM_ERROR or UVM_FATAL count is greater than 0.

    It does NOT fail only because words like FAILED or WARNING appear in logs.
    """

    text = (raw_output or "") + "\n" + (combined_log or "")
    text_lower = text.lower()

    # 1. Process-level failure.
    if returncode != 0:
        return True

    # 2. Real Vivado/SystemVerilog blocking errors.
    hard_error_markers = [
        "ERROR:",
        "FATAL:",
        "syntax error",
        "elaboration failed",
        "compilation failed",
    ]

    if any(marker.lower() in text_lower for marker in hard_error_markers):
        return True

    # 3. UVM summary counts. Only fail if count > 0.
    uvm_error_match = re.search(r"UVM_ERROR\s*:\s*(\d+)", text)
    if uvm_error_match and int(uvm_error_match.group(1)) > 0:
        return True

    uvm_fatal_match = re.search(r"UVM_FATAL\s*:\s*(\d+)", text)
    if uvm_fatal_match and int(uvm_fatal_match.group(1)) > 0:
        return True

    return False

def read_text_file_safe(path: str) -> str:
    """
    Reads a text file safely. Used for combined_xsim.log.
    """

    if not path or not os.path.exists(path):
        return ""

    try:
        with open(path, "r", encoding="utf-8", errors="ignore") as f:
            return f.read()
    except Exception as e:
        print(f"[CHECKER WARNING] Could not read log file {path}: {e}")
        return ""

def parse_vivado_failure(raw_output: str):
    if "not recognized" in raw_output:
        return "SYSTEM ERROR: Vivado path incorrect.", "System/Path Error"

    error_lines = []

    for line in raw_output.split("\n"):
        line_lower = line.lower()

        # Real Vivado/SystemVerilog errors
        if (
            "ERROR:" in line
            or "FATAL:" in line
            or "syntax error" in line_lower
            or "elaboration failed" in line_lower
            or "compilation failed" in line_lower
        ):
            error_lines.append(line)
            continue

        # UVM errors only if count > 0
        m_err = re.search(r"UVM_ERROR\s*:\s*(\d+)", line)
        if m_err and int(m_err.group(1)) > 0:
            error_lines.append(line)
            continue

        m_fat = re.search(r"UVM_FATAL\s*:\s*(\d+)", line)
        if m_fat and int(m_fat.group(1)) > 0:
            error_lines.append(line)
            continue

    if error_lines:
        errors = "\n".join(error_lines[:20])
    else:
        errors = (
            "Vivado/XSim returned a failure status, but no explicit blocking "
            "ERROR, FATAL, UVM_ERROR > 0, or UVM_FATAL > 0 was found."
        )

    return errors, "Vivado Execution Error"


# =====================================================
# ------ EXPERIENCE MEMORY ------
# =====================================================
def save_error_experience_if_fixed(state: AgentState):
    """
    If there was a previous compilation error and the new run succeeds,
    save the generated working code as a positive fixing experience.
    """

    previous_error = state.get("compilation_error", "")
    code = state.get("generated_code", "")
    clean_code = extract_code(code) if code else ""

    if not previous_error or "SYSTEM ERROR" in previous_error:
        return

    exp_dir = os.path.join("..", "results", "experience_data")
    os.makedirs(exp_dir, exist_ok=True)

    clean_ts = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    exp_file_path = os.path.join(exp_dir, f"fix_{clean_ts}.txt")

    memory_entry = (
        f"VIVADO_ERROR_DESCRIPTION:\n{previous_error}\n\n"
        f"VERIFIED_WORKING_CODE:\n{clean_code}\n"
    )

    with open(exp_file_path, "w", encoding="utf-8") as f:
        f.write(memory_entry)

    print(f"[LONG TERM MEMORY]: Experience saved in {exp_file_path}")


# =====================================================
# ------ COVERAGE REPORT VALIDATION ------
# =====================================================
def validate_coverage_report(report_file_path: str):
    if not os.path.exists(report_file_path):
        return (
            Status.FAILED,
            "Coverage Report Missing",
            "N/A",
            "Vivado ran successfully, but coverage report was not generated."
        )

    if os.path.getsize(report_file_path) == 0:
        return (
            Status.FAILED,
            "Coverage Report Empty",
            "N/A",
            "Coverage report exists but is empty."
        )

    coverage_val = extract_coverage_percent(report_file_path)

    if coverage_val is None or coverage_val == "N/A":
        return (
            Status.FAILED,
            "Coverage Parse Error",
            "N/A",
            "Coverage report exists, but coverage percentage could not be extracted."
        )

    return Status.SUCCESS, "None", coverage_val, ""


# =====================================================
# ------- CHECKER NODE ------
# =====================================================
def checker_node(state: AgentState):
    print("\n[CHECKER]: Validate code...")

    paths = prepare_checker_paths()

    clean_old_simulation_logs(paths["working_dir"])

    returncode, raw_output, exec_time = execute_vivado(
        paths["bat_file_path"],
        paths["working_dir"]
    )

    combined_log_path = build_combined_simulation_log(
    paths["working_dir"],
    raw_output
    )


    combined_log_text = read_text_file_safe(combined_log_path)
    full_error_text = raw_output + "\n" + combined_log_text

    if has_vivado_error(returncode, raw_output, combined_log_text):
        errors, error_summary = parse_vivado_failure(full_error_text)
        status = Status.FAILED
        coverage_val = "N/A"

        if state.get("generated_code"):
            save_negative_experience(
                state.get("current_hole", {}).get("description", ""),
                state.get("generated_code", ""),
                errors
            )

        print(f"Compilation FAILED (Time: {exec_time}s):\n{errors}")

    else:
        save_error_experience_if_fixed(state)

        status, error_summary, coverage_val, errors = validate_coverage_report(
            paths["report_file_path"]
        )

        if status == Status.SUCCESS:
            print(f"Compilation & Simulation SUCCESSFUL | Time exec: {exec_time} sec")
        else:
            print(f"Error: {errors}")

    save_checker_metrics(
        state,
        status,
        exec_time,
        coverage_val,
        error_summary,
        errors
    )

    print(f"[DEBUG CHECKER] Final coverage_val: {coverage_val}")
    print(f"[DEBUG CHECKER] Combined simulation log: {combined_log_path}")

    return {
        "status": status,
        "compilation_error": errors,
        "fcov_report_path": paths["report_file_path"] if status == Status.SUCCESS else "",
        "simulation_log_path": combined_log_path if os.path.exists(combined_log_path) else "",
    }