import os
import re
import time
import datetime
import subprocess
from state import AgentState
from scripts.utils_files.results_saving import save_to_csv, save_to_file
from utils_files.memory import save_negative_experience
from utils_files.file_ops import extract_code
from utils_files.status import Status
from utils_files.coverage import extract_coverage_percent
from config import PROJECT_CONFIG


# =====================================================
# ------ FUNCTION FOR VIVADO EXECUTION------
# =====================================================
def execute_vivado(bat_file_path: str, working_dir: str):
    start_time = time.time()            # counting time for metrics

    try:
        result = subprocess.run(
            [bat_file_path], 
            cwd=working_dir,      
            capture_output=True, 
            text=True, 
            shell=True,
            timeout = 300      
        )

        # gettinf compilation errors and return code generated
        raw_errors = result.stdout + "\n" + result.stderr
        returncode = result.returncode

    except subprocess.TimeoutExpired:
        print("VIVADO timeout")
        raw_errors = "ERROR: Timeout - Vivado simulation or compilation hanged."
        returncode = 1

    end_time = time.time()
    exec_time = round(end_time - start_time, 2)

    return returncode, raw_errors, exec_time



# =====================================================
# ------ FUNCTION FOR SAVING METRICS ------
# =====================================================
def save_checker_metrics(state: AgentState, status: Status, exec_time: float, coverage_val: str, error_summary: str, raw_errors: str ):
    '''Save experimental data in csv and txt files'''
    results_dir = os.path.join("..","results")
    os.makedirs(results_dir, exist_ok=True)

    ''' TXT and CSV file path'''
    raport_path = os.path.join(results_dir, "raport_experimental.txt")
    csv_path = os.path.join(results_dir, "experimental_metrics_FIFO3.csv")

    timestamp = datetime.datetime.now().strftime("%m/%d/%Y %H:%M")
    it = state.get("iterations", 0)
    tokens = state.get("iteration_tokens", 0)

    # Save to TXT
    content_txt = f"[{timestamp}] Iteration: {it} | Status: {status.value} | Coverage: {coverage_val} | Time_exec: {exec_time}s\n"
    if status == Status.FAILED:
        content_txt += f"Errors:\n{raw_errors}\n"
    save_to_file(content_txt, raport_path)

    # Save to CSV
    content_csv = [timestamp, it, status.value, exec_time, coverage_val, error_summary, tokens]
    save_to_csv(content_csv, csv_path)


def prepare_checker_paths():
    bat_file_path = PROJECT_CONFIG["bat_file_path"]
    working_dir = os.path.dirname(bat_file_path)

    return {
        "bat_file_path": bat_file_path,
        "working_dir": working_dir,
        "report_file_path": os.path.join(
            working_dir,
            "coverage_report_text",
            "functionalCoverageReport",
            "xcrg_func_cov_report.txt"
        ),
        "sim_log_path": os.path.join(working_dir, "combined_xsim.log")
    }


def is_current_test_log(filename: str) -> bool:
    """
    Accepts only intentional test logs generated by MakeSVfile.bat.
    Rejects Vivado backup logs such as xsim_13564.backup.log.
    """
    return (
        filename.startswith("xsim_test")
        and filename.endswith(".log")
        and ".backup." not in filename
    )


def clean_old_simulation_logs(working_dir: str):
    """
    Removes old xsim test logs before a new Vivado run.
    This prevents the Analyzer from reading stale logs from previous runs.
    """
    try:
        for filename in os.listdir(working_dir):
            if is_current_test_log(filename) or filename == "combined_xsim.log":
                os.remove(os.path.join(working_dir, filename))
    except Exception as e:
        print(f"[CHECKER WARNING] Could not clean old simulation logs: {e}")


def build_combined_simulation_log(working_dir: str, raw_output: str = "") -> str:
    """
    Collects Vivado stdout/stderr and all xsim test logs into a single combined log file.
    This gives the Analyzer access to compilation, elaboration, simulation, and test logs.
    """
    combined_log_path = os.path.join(working_dir, "combined_xsim.log")

    log_files = []

    try:
        for filename in os.listdir(working_dir):
            if is_current_test_log(filename):
                log_files.append(filename)

        log_files = sorted(log_files)

        with open(combined_log_path, "w", encoding="utf-8", errors="ignore") as out:
            out.write("===== VIVADO STDOUT / STDERR =====\n")
            if raw_output.strip():
                out.write(raw_output)
            else:
                out.write("[INFO] No Vivado stdout/stderr captured.\n")

            if not log_files:
                out.write("\n\n[WARNING] No xsim_*.log files found.\n")

                fallback_log = os.path.join(working_dir, "xsim.log")
                if os.path.exists(fallback_log):
                    out.write("\n===== FALLBACK: xsim.log =====\n")
                    with open(fallback_log, "r", encoding="utf-8", errors="ignore") as f:
                        out.write(f.read())
                else:
                    out.write("[WARNING] xsim.log fallback was also not found.\n")

            for log_file in log_files:
                log_path = os.path.join(working_dir, log_file)
                out.write(f"\n\n===== {log_file} =====\n")
                with open(log_path, "r", encoding="utf-8", errors="ignore") as f:
                    out.write(f.read())

    except Exception as e:
        with open(combined_log_path, "w", encoding="utf-8", errors="ignore") as out:
            out.write(f"[ERROR] Failed to build combined simulation log: {e}\n")

    return combined_log_path


def has_vivado_error(returncode: int, raw_output: str) -> bool:
    return returncode != 0 or "ERROR:" in raw_output


def parse_vivado_failure(raw_output: str):
    if "not recognized" in raw_output:
        return "SYSTEM ERROR: Vivado path incorrect.", "System/Path Error"

    error_lines = [
        line for line in raw_output.split("\n")
        if "ERROR:" in line or "FATAL:" in line or "CRITICAL WARNING:" in line
    ]

    if error_lines:
        errors = "\n".join(error_lines[:15])
    else:
        lines = [line for line in raw_output.split("\n") if line.strip()]
        errors = "\n".join(lines[-30:]) if lines else "Unknown Vivado failure. No output captured."

    return errors, "Vivado Execution Error"

def save_error_experience_if_fixed(state: AgentState):
    previous_error = state.get("compilation_error", "")
    code = state.get("generated_code", "")
    clean_code = extract_code(code) if code else ""

    if not previous_error or "SYSTEM ERROR" in previous_error:
        return

    exp_dir = os.path.join("..", "results", "experience_data")
    os.makedirs(exp_dir, exist_ok=True)

    clean_ts = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    exp_file_path = os.path.join(exp_dir, f"fix_{clean_ts}.txt")

    memory_entry = (
        f"VIVADO_ERROR_DESCRIPTION:\n{previous_error}\n\n"
        f"VERIFIED_WORKING_CODE:\n{clean_code}\n"
    )

    with open(exp_file_path, "w", encoding="utf-8") as f:
        f.write(memory_entry)

    print(f"[LONG TERM MEMORY]: Experience saved in {exp_file_path}")


def validate_coverage_report(report_file_path: str):
    if not os.path.exists(report_file_path):
        return (
            Status.FAILED,
            "Coverage Report Missing",
            "N/A",
            "Vivado ran successfully, but coverage report was not generated."
        )

    if os.path.getsize(report_file_path) == 0:
        return (
            Status.FAILED,
            "Coverage Report Empty",
            "N/A",
            "Coverage report exists but is empty."
        )

    coverage_val = extract_coverage_percent(report_file_path)

    if coverage_val is None or coverage_val == "N/A":
        return (
            Status.FAILED,
            "Coverage Parse Error",
            "N/A",
            "Coverage report exists, but coverage percentage could not be extracted."
        )

    return Status.SUCCESS, "None", coverage_val, ""
# =====================================================
# ------- CHECKER NODE ------
# =====================================================
def checker_node(state: AgentState):
    print("\n[CHECKER]: Validate code...")

    paths = prepare_checker_paths()
    clean_old_simulation_logs(paths["working_dir"])
    returncode, raw_output, exec_time = execute_vivado(
        paths["bat_file_path"],
        paths["working_dir"]
    )
    combined_log_path = build_combined_simulation_log(paths["working_dir"], raw_output)
    if has_vivado_error(returncode, raw_output):
        errors, error_summary = parse_vivado_failure(raw_output)
        status = Status.FAILED
        coverage_val = "N/A"
        if state.get("generated_code"):
            save_negative_experience(
                state.get("current_hole", {}).get("description", ""),
                state.get("generated_code", ""),
                errors
            )

        print(f"Compilation FAILED (Time: {exec_time}s): \n {errors}")

    else:
        save_error_experience_if_fixed(state)

        status, error_summary, coverage_val, errors = validate_coverage_report(
            paths["report_file_path"]
        )

        if status == Status.SUCCESS:
            print(f"Compilation & Simulation SUCCESSFUL | Time exec: {exec_time} sec")
        else:
            print(f"Error: {errors}")

    save_checker_metrics(
        state,
        status,
        exec_time,
        coverage_val,
        error_summary,
        errors
    )

    print(f"[DEBUG CHECKER] Final coverage_val: {coverage_val}")
    print(f"[DEBUG CHECKER] Combined simulation log: {combined_log_path}")

    return {
        "status": status,
        "compilation_error": errors,
        "fcov_report_path": paths["report_file_path"] if status == Status.SUCCESS else "",
        "simulation_log_path": combined_log_path if os.path.exists(combined_log_path) else "",

    }