import os
from dotenv import load_dotenv
from llama_index.core import Settings, StorageContext, load_index_from_storage
from llama_index.llms.groq import Groq
from llama_index.embeddings.huggingface import HuggingFaceEmbedding

# load environment variables
load_dotenv()

# initialize LLM
llm = Groq(model="llama-3.3-70b-versatile")
# initialize the embedding
embed_model=HuggingFaceEmbedding(model_name="BAAI/bge-small-en-v1.5")

# global settings
Settings.llm=llm
Settings.embed_model=embed_model

# load indices generated 
def load_rag_indices():
    print("Loading indices!\n\n")

    storage_context_static=StorageContext.from_defaults(persist_dir="../DOCS/storage_static")
    static_index = load_index_from_storage(storage_context_static)

    storage_context_dynamic = StorageContext.from_defaults(persist_dir="../DOCS/storage_dynamic")
    dynamic_index = load_index_from_storage(storage_context_dynamic)

    return static_index, dynamic_index


def analyzer_agent():
    print("---------- Analyzer agent starts! ----------")

    # load indices
    static_index, dynamic_index = load_rag_indices()
    
    # creating query engines
    static_query_engine = static_index.as_query_engine(similarity_top_k = 3)
    dynamic_query_engine = dynamic_index.as_query_engine(similarity_top_k = 3)

    # interogating dynamic storage
    print("--- Querying RAG for DUT specification (dynamic_query) ---")
    dut_context =  dynamic_query_engine.query(
        "What are the signals, parameters, and operations for the Synchronous FIFO? "
        "What are the exact conditions for the full and empty signals?"
    )

    # interogating static storage
    print("--- Querying RAG for Functional Coverage and UVM rules (static_query) ---")
    rules_context = static_query_engine.query(
        "What is the uvm_subscriber class and how does it implement the write() method? "
        "How are covergroups, coverpoints, and crosses correctly defined in SystemVerilog?"
    )

    # build the prompt for large language model
    system_prompt = """You are a Senior Verification Engineer, expert in SystemVerilog and UVM.
Your task: Analyze the provided specifications and formulate a clear 'Action Plan' as a structured list to write a coverage_container class (extended from uvm_subscriber).
You must clearly specify what covergroups, coverpoints (including bins), and crosses are necessary to achieve 100% --> functional coverage.

STRICT RULE: DO NOT write the complete SystemVerilog code! Only formulate the logical plan that a Generation Agent will follow to write the code."""

    user_prompt = f"""
Base your response STRICTLY on the extracted information below:

--- DUT SPECIFICATIONS (FIFO) ---
{dut_context}

--- UVM/SV RULES ---
{rules_context}

Analyze this data and generate the Action Plan. Be structured and technical.
"""

    # call the LLM 
    print(" \n Waiting for LLM to analyzing and respond! \n")
    response = llm.complete(system_prompt + "\n\n" + user_prompt)

    print("\n------------------------------------------\n")
    print("-----------Plan generated by agent------------")
    print("\n------------------------------------------\n")

    print(response.text)


if __name__ == "__main__":
    analyzer_agent()


