import os 
from dotenv import load_dotenv
from llama_index.core import Settings, StorageContext, load_index_from_storage
from llama_index.llms.groq import Groq
from llama_index.embeddings.huggingface import HuggingFaceEmbedding

# load environment variables
load_dotenv()

# initialize LLM
llm = Groq(model="llama-3.3-70b-versatile")
# initialize the embedding
embed_model=HuggingFaceEmbedding(model_name="BAAI/bge-small-en-v1.5")

# global settings
Settings.llm=llm
Settings.embed_model=embed_model

# load static index
def load_static_index():
    """
    Load only the static index for syntax rules
    """

    print("\nLoading static index for syntax rules...\n")

    storage_context = StorageContext.from_defaults(persist_dir="../DOCS/storage_static")
    static_index = load_index_from_storage(storage_context)

    return static_index

# generation function
def generator_agent():
    print("---------- Generator agent starts! ----------")

    static_index = load_static_index()

    #query the static RAG for syntax example
    query_engine = static_index.as_query_engine(similarity_top_k = 2)
    print("Querying  RAG for SV syntax....")

    syntax_context = query_engine.query(
       "Show me the exact SystemVerilog syntax for defining a covergroup with coverpoints, bins, and crosses. "
        "Also, show how to properly extend a uvm_subscriber and implement the write() phase."
    )

    # hardcoded action plan
    action_plan = """
### Action Plan: Coverage Container Class for Synchronous FIFO

#### I. Class Definition and Inheritance
1. Define a new class `fifo_coverage_container` that extends `uvm_subscriber`.
2. This class will encapsulate the analysis export and implement the write method for transaction processing.

#### II. Covergroups and Coverpoints
1. **FIFO State Covergroup**:
   - Coverpoints: `full_signal`, `empty_signal`.
   - Bins: For `full_signal` and `empty_signal`, create bins for each possible state (e.g., HIGH, LOW).
2. **Write Operation Covergroup**:
   - Coverpoints: `write_enable` (we), `data_in` (0 to 2^32-1).
   - Bins: `WRITE_ENABLED`, `WRITE_DISABLED`. For `data_in`, consider generic ranges.
3. **Read Operation Covergroup**:
   - Coverpoints: `read_enable` (re), `data_out` (0 to 2^32-1).
   - Bins: `READ_ENABLED`, `READ_DISABLED`.
4. **Reset Operation Covergroup**:
   - Coverpoints: `reset`.
   - Bins: `RESET_ACTIVE`, `RESET_INACTIVE`.

#### III. Cross Coverage
1. **Write and Read Cross**: Cross `write_enable` with `read_enable`.
2. **Data In and Out Cross**: Cross `data_in` with `data_out`.
3. **FIFO State and Operations Cross**: Cross `full_signal` and `empty_signal` with `write_enable` and `read_enable`.

#### IV. Implementation
1. Implement the `write` method to sample and trigger coverage based on the analysis transactions received (e.g., `t.full_signal`, `t.data_in`).
    """

    # 4. Build the Prompts
    system_prompt = """You are an Expert SystemVerilog and UVM Developer. 
Your ONLY task is to write clean, compilable, and production-ready SystemVerilog code based on an Action Plan.
STRICT RULES:
1. Output ONLY the SystemVerilog code inside a ```systemverilog ... ``` code block.
2. DO NOT write any conversational text, explanations, or pleasantries before or after the code block.
3. Use proper UVM macros (`uvm_component_utils`).
4. Ensure the covergroups are instantiated in the constructor (new function) and sampled in the write() method.
5. Assume the transaction class is named `fifo_seq_item`.
"""

    user_prompt = f"""
Write the `fifo_coverage_container.sv` class based strictly on this Action Plan:
{action_plan}

Ensure your syntax is perfect, using these rules as reference:
{syntax_context}
"""
    
    # generating the code
    response = llm.complete(system_prompt + "\n\n" + user_prompt)

    print("\n------------------------------------------\n")
    print("-----------Code generated by agent------------")
    print("\n------------------------------------------\n")

    print(response.text)



if __name__ == "__main__":
    generator_agent()
