from typing import TypedDict, List

# agent state class
class AgentState(TypedDict):
    # -- simulation environment --
    uvm_rules:                  str             # static documentation
    dut_specs:                  str             # dynamic documentation
    simulation_log_path:        str             # xsim.log absolute path
    fcov_report_path:           str             # FCOV report absolute path
    coverage_value:             float           # coverage %

    # -- coverage analysis --
    coverage_holes:             str             # raw string used for compatibility
    holes_list:                 List[dict]      # structured list generated by analyzer
    previous_holes_list:        List[dict]      # previous list used for comparison --> deleted in next step
    current_hole:               dict            # curent hole

    # -- analysis results --
    root_cause_hole:            str             # why the hole was note covered
    action_plan:                str             # instruction for generator to resolve the problem 
    tareget_file:               str

    # -- generation code --
    generated_code:             str
    compilation_error:          str             # TLM for generator agent
    iterations:                 int
    
    # -- flow control --
    analyzer_mode:              str             # analize FCOV and logs, build_holes_list, root_cause or compare_results
    status:                     str             # FAILED, SUCCESS, ANALYSIS_COMPLETE
    user_command:               str             # user interaction 

    # -- TLM for analyzer agent --
    stimulus_memory_path:       str

    iteration_tokens:           int             # iteration_tokens for statistics and metrics
   # -- UI Communication --
    ui_message:                 str             # formatted message for UI display
    ui_input:                   str             # user input from UI
   