from typing import TypedDict, List
from utils_files.status import Status
from utils_files.phases import Phase

# agent state class
class AgentState(TypedDict):
    # -- simulation environment --
    uvm_rules:                  str             # static documentation
    dut_specs:                  str             # dynamic documentation
    simulation_log_path:        str             # xsim.log absolute path
    fcov_report_path:           str             # FCOV report absolute path
    coverage_value:             float           # coverage %
    previous_coverage:           float

    # -- coverage analysis --
    coverage_holes:             str             # raw string used for compatibility
    holes_list:                 List[dict]      # structured list generated by analyzer
    previous_holes_list:        List[dict]      # previous list used for comparison --> deleted in next step
    current_hole:               dict            # curent hole
    rollback_files:             dict

    # -- analysis results --
    root_cause_hole:            str             # why the hole was note covered
    action_plan:                str             # instruction for generator to resolve the problem 
    target_file:               str

    # -- generation code --
    generated_code:             str
    compilation_error:          str             # TLM for generator agent
    iterations:                 int
    
    # -- flow control --
    status:                     Status             # FAILED, SUCCESS, PROCESSING
    phase:                      Phase              # current phase of the process
    user_command:               str             # user interaction 
    user_feedback:              str             # user feedback after fix implementation
    

    # -- TLM for analyzer agent --
    stimulus_memory_path:       str

    iteration_tokens:           int             # iteration_tokens for statistics and metrics
   # -- UI Communication --
    ui_message:                 str             # formatted message for UI display
    ui_input:                   str             # user input from UI
   