from enum import Enum

class Phase(str, Enum):

    INIT = "INIT"

    RUN_CHECKER = "RUN_CHECKER"

    BUILD_HOLES_LIST = "BUILD_HOLES_LIST"

    SELECT_HOLE = "SELECT_HOLE"

    ROOT_CAUSE_ANALYSIS = "ROOT_CAUSE_ANALYSIS"

    PLAN_REVIEW = "PLAN_REVIEW"

    CODE_GENERATION = "CODE_GENERATION"

    CODE_REVIEW = "CODE_REVIEW"

    RUN_AFTER_FIX = "RUN_AFTER_FIX"

    COMPARE_RESULTS = "COMPARE_RESULTS"
    RESULT_REVIEW = "RESULT_REVIEW"
    ROLLBACK = "ROLLBACK"

    ERROR_ANALYSIS = "ERROR_ANALYSIS"

    DONE = "DONE"

