import os
import re
import shutil
import time
import datetime
import glob
import subprocess

from state import AgentState
from utils_files.results_saving import save_to_csv, save_to_file
from utils_files.memory import save_negative_experience
from utils_files.file_ops import extract_code
from utils_files.status import Status
from utils_files.coverage import extract_coverage_percent
from config import PROJECT_CONFIG


# =====================================================
# ------ FUNCTION FOR VIVADO EXECUTION ------
# =====================================================
def execute_vivado(bat_file_path: str, working_dir: str):
    start_time = time.time()

    try:
        result = subprocess.run(
            [bat_file_path],
            cwd=working_dir,
            capture_output=True,
            text=True,
            shell=True,
            timeout=300
        )

        raw_output = result.stdout + "\n" + result.stderr
        returncode = result.returncode

    except subprocess.TimeoutExpired:
        print("VIVADO timeout")
        raw_output = "ERROR: Timeout - Vivado simulation or compilation hanged."
        returncode = 1

    end_time = time.time()
    exec_time = round(end_time - start_time, 2)

    return returncode, raw_output, exec_time


def prepare_checker_paths():
    bat_file_path = PROJECT_CONFIG["bat_file_path"]
    working_dir = os.path.dirname(bat_file_path)

    return {
        "bat_file_path": bat_file_path,
        "working_dir": working_dir,
        "report_file_path": os.path.join(
            working_dir,
            "coverage_report_text",
            "functionalCoverageReport",
            "xcrg_func_cov_report.txt"
        ),
        "sim_log_path": os.path.join(working_dir, "combined_xsim.log")
    }


# =====================================================
# ------ LOG FILE HANDLING ------
# =====================================================
def is_current_test_log(filename: str) -> bool:
    """
    Accepts only intentional test logs generated by MakeSVfile.bat.
    Rejects Vivado backup logs such as xsim_13564.backup.log.
    """

    return (
        filename.startswith("xsim_test")
        and filename.endswith(".log")
        and ".backup." not in filename
    )


def clean_old_simulation_logs(working_dir: str):
    """
    Removes old xsim test logs before a new Vivado run.
    This prevents the Analyzer from reading stale logs from previous runs.
    """

    try:
        for filename in os.listdir(working_dir):
            path = os.path.join(working_dir, filename)

            if (
                is_current_test_log(filename)
                or filename == "combined_xsim.log"
                or filename.startswith("xsim") and filename.endswith(".log")
                or filename.startswith("xvlog") and filename.endswith(".log")
                or filename.startswith("xelab") and filename.endswith(".log")
                or filename.startswith("xcrg") and filename.endswith(".log")
                or filename.startswith("vivado") and filename.endswith(".log")
                or filename.startswith("vivado") and filename.endswith(".jou")
            ):
                try:
                    os.remove(path)
                    print(f"[CHECKER CLEANUP] Removed file: {path}")
                except Exception as e:
                    print(f"[CHECKER WARNING] Could not remove {path}: {e}")

    except Exception as e:
        print(f"[CHECKER WARNING] Could not scan simulation directory: {e}")


def build_combined_simulation_log(working_dir: str, raw_output: str = "") -> str:
    """
    Collects Vivado stdout/stderr and all current xsim test logs into one file.
    Backup logs are intentionally ignored.
    """

    combined_log_path = os.path.join(working_dir, "combined_xsim.log")
    log_files = []

    try:
        for filename in os.listdir(working_dir):
            if is_current_test_log(filename):
                log_files.append(filename)

        log_files = sorted(log_files)

        with open(combined_log_path, "w", encoding="utf-8", errors="ignore") as out:
            out.write("===== VIVADO STDOUT / STDERR =====\n")

            if raw_output.strip():
                out.write(raw_output)
            else:
                out.write("[INFO] No Vivado stdout/stderr captured.\n")

            if not log_files:
                out.write("\n\n[WARNING] No xsim_test*.log files found.\n")

                fallback_log = os.path.join(working_dir, "xsim.log")

                if os.path.exists(fallback_log):
                    out.write("\n===== FALLBACK: xsim.log =====\n")
                    with open(fallback_log, "r", encoding="utf-8", errors="ignore") as f:
                        out.write(f.read())
                else:
                    out.write("[WARNING] xsim.log fallback was also not found.\n")

            for log_file in log_files:
                log_path = os.path.join(working_dir, log_file)

                out.write(f"\n\n===== {log_file} =====\n")

                with open(log_path, "r", encoding="utf-8", errors="ignore") as f:
                    out.write(f.read())

    except Exception as e:
        with open(combined_log_path, "w", encoding="utf-8", errors="ignore") as out:
            out.write(f"[ERROR] Failed to build combined simulation log: {e}\n")

    return combined_log_path


# =====================================================
# ------ VIVADO ERROR PARSING ------
# =====================================================
def has_vivado_error(returncode: int, raw_output: str, combined_log: str = "") -> bool:
    """
    Detects only real blocking errors.

    A run is considered failed only when:
    - Vivado/XSim returns a non-zero process code;
    - Vivado reports a real compile/elaboration error;
    - UVM_ERROR or UVM_FATAL count is greater than 0.

    It does NOT fail only because words like FAILED or WARNING appear in logs.
    """

    text = (raw_output or "") + "\n" + (combined_log or "")
    text_lower = text.lower()

    # 1. Process-level failure.
    if returncode != 0:
        return True

    # 2. Real Vivado/SystemVerilog blocking errors.
    hard_error_markers = [
        "ERROR:",
        "FATAL:",
        "syntax error",
        "elaboration failed",
        "compilation failed",
    ]

    if any(marker.lower() in text_lower for marker in hard_error_markers):
        return True

    # 3. UVM summary counts. Only fail if count > 0.
    uvm_error_match = re.search(r"UVM_ERROR\s*:\s*(\d+)", text)
    if uvm_error_match and int(uvm_error_match.group(1)) > 0:
        return True

    uvm_fatal_match = re.search(r"UVM_FATAL\s*:\s*(\d+)", text)
    if uvm_fatal_match and int(uvm_fatal_match.group(1)) > 0:
        return True

    return False

def read_text_file_safe(path: str) -> str:
    """
    Reads a text file safely. Used for combined_xsim.log.
    """

    if not path or not os.path.exists(path):
        return ""

    try:
        with open(path, "r", encoding="utf-8", errors="ignore") as f:
            return f.read()
    except Exception as e:
        print(f"[CHECKER WARNING] Could not read log file {path}: {e}")
        return ""

def parse_vivado_failure(raw_output: str):
    if "not recognized" in raw_output:
        return "SYSTEM ERROR: Vivado path incorrect.", "System/Path Error"

    error_lines = []

    for line in raw_output.split("\n"):
        line_lower = line.lower()

        # Real Vivado/SystemVerilog errors
        if (
            "ERROR:" in line
            or "FATAL:" in line
            or "syntax error" in line_lower
            or "elaboration failed" in line_lower
            or "compilation failed" in line_lower
        ):
            error_lines.append(line)
            continue

        # UVM errors only if count > 0
        m_err = re.search(r"UVM_ERROR\s*:\s*(\d+)", line)
        if m_err and int(m_err.group(1)) > 0:
            error_lines.append(line)
            continue

        m_fat = re.search(r"UVM_FATAL\s*:\s*(\d+)", line)
        if m_fat and int(m_fat.group(1)) > 0:
            error_lines.append(line)
            continue

    if error_lines:
        errors = "\n".join(error_lines[:20])
    else:
        errors = (
            "Vivado/XSim returned a failure status, but no explicit blocking "
            "ERROR, FATAL, UVM_ERROR > 0, or UVM_FATAL > 0 was found."
        )

    return errors, "Vivado Execution Error"
