import os
import re
import time
import subprocess
from state import AgentState
from config import PROJECT_CONFIG

# Utility functions for running Vivado/XSim and analyzing simulation errors.

def execute_vivado(bat_file_path: str, working_dir: str):
    """Executes the Vivado/XSim run script and returns its output and execution time."""
    start_time = time.time()
    # Vivado/XSim execution.
    try:
        result = subprocess.run(
            [bat_file_path],
            cwd=working_dir,
            capture_output=True,
            text=True,
            shell=True,
            timeout=300
        )

        raw_output = result.stdout + "\n" + result.stderr
        returncode = result.returncode

    except subprocess.TimeoutExpired:
        print("VIVADO timeout")
        raw_output = "ERROR: Timeout - Vivado simulation or compilation hanged."
        returncode = 1

    end_time = time.time()
    exec_time = round(end_time - start_time, 2)

    return returncode, raw_output, exec_time


def prepare_checker_paths():
    """Builds the main file paths used by the Checker node."""
    bat_file_path = PROJECT_CONFIG["bat_file_path"]
    working_dir = os.path.dirname(bat_file_path)

    return {
        "bat_file_path": bat_file_path,
        "working_dir": working_dir,
        "report_file_path": os.path.join(
            working_dir,
            "coverage_report_text",
            "functionalCoverageReport",
            "xcrg_func_cov_report.txt"
        ),
        "sim_log_path": os.path.join(working_dir, "combined_xsim.log")
    }


def is_current_test_log(filename: str) -> bool:
    """
    Accepts only intentional test logs generated by MakeSVfile.bat.
    Rejects Vivado backup logs such as xsim_13564.backup.log.
    """
    return (
        filename.startswith("xsim_test")
        and filename.endswith(".log")
        and ".backup." not in filename
    )


def clean_old_simulation_logs(working_dir: str):
    """
    Removes old xsim test logs before a new Vivado run.
    This prevents the Analyzer from reading stale logs from previous runs.
    """
    try:
        for filename in os.listdir(working_dir):
            path = os.path.join(working_dir, filename)

            if (
                is_current_test_log(filename)
                or filename == "combined_xsim.log"
                or filename.startswith("xsim") and filename.endswith(".log")
                or filename.startswith("xvlog") and filename.endswith(".log")
                or filename.startswith("xelab") and filename.endswith(".log")
                or filename.startswith("xcrg") and filename.endswith(".log")
                or filename.startswith("vivado") and filename.endswith(".log")
                or filename.startswith("vivado") and filename.endswith(".jou")
            ):
                try:
                    os.remove(path)
                    print(f"[CHECKER CLEANUP] Removed file: {path}")
                except Exception as e:
                    print(f"[CHECKER WARNING] Could not remove {path}: {e}")

    except Exception as e:
        print(f"[CHECKER WARNING] Could not scan simulation directory: {e}")


def build_combined_simulation_log(working_dir: str, raw_output: str = "") -> str:
    """
    Collects Vivado stdout/stderr and all current xsim test logs into one file, backup logs are ignored.
    """
    combined_log_path = os.path.join(working_dir, "combined_xsim.log")
    log_files = []

    try:
        for filename in os.listdir(working_dir):
            if is_current_test_log(filename):
                log_files.append(filename)

        log_files = sorted(log_files)

        with open(combined_log_path, "w", encoding="utf-8", errors="ignore") as out:
            out.write("===== VIVADO STDOUT / STDERR =====\n")

            if raw_output.strip():
                out.write(raw_output)
            else:
                out.write("[INFO] No Vivado stdout/stderr captured.\n")

            if not log_files:
                out.write("\n\n[WARNING] No xsim_test*.log files found.\n")

                fallback_log = os.path.join(working_dir, "xsim.log")

                if os.path.exists(fallback_log):
                    out.write("\n===== FALLBACK: xsim.log =====\n")
                    with open(fallback_log, "r", encoding="utf-8", errors="ignore") as f:
                        out.write(f.read())
                else:
                    out.write("[WARNING] xsim.log fallback was also not found.\n")

            for log_file in log_files:
                log_path = os.path.join(working_dir, log_file)

                out.write(f"\n\n===== {log_file} =====\n")

                with open(log_path, "r", encoding="utf-8", errors="ignore") as f:
                    out.write(f.read())

    except Exception as e:
        with open(combined_log_path, "w", encoding="utf-8", errors="ignore") as out:
            out.write(f"[ERROR] Failed to build combined simulation log: {e}\n")

    return combined_log_path


def has_vivado_error(returncode: int, raw_output: str, combined_log: str = "") -> bool:
    """
    Detects only real blocking errors.

    A run is considered failed only when:
    - Vivado/XSim returns a non-zero process code;
    - Vivado reports a real compile/elaboration error;
    - UVM_ERROR or UVM_FATAL count is greater than 0.

    It does NOT fail only because words like FAILED or WARNING appear in logs.
    """
    text = (raw_output or "") + "\n" + (combined_log or "")
    text_lower = text.lower()

    # Process-level failure.
    if returncode != 0:
        return True

    # Real Vivado/SystemVerilog blocking errors.
    hard_error_markers = [
        "ERROR:",
        "FATAL:",
        "syntax error",
        "elaboration failed",
        "compilation failed",
    ]

    if any(marker.lower() in text_lower for marker in hard_error_markers):
        return True

    # UVM summary counts. Only fail if count > 0.
    uvm_error_match = re.search(r"UVM_ERROR\s*:\s*(\d+)", text)
    if uvm_error_match and int(uvm_error_match.group(1)) > 0:
        return True

    uvm_fatal_match = re.search(r"UVM_FATAL\s*:\s*(\d+)", text)
    if uvm_fatal_match and int(uvm_fatal_match.group(1)) > 0:
        return True

    return False


def read_text_file_safe(path: str) -> str:
    """Reads a text file safely. Used for combined_xsim.log."""

    if not path or not os.path.exists(path):
        return ""

    try:
        with open(path, "r", encoding="utf-8", errors="ignore") as f:
            return f.read()
    except Exception as e:
        print(f"[CHECKER WARNING] Could not read log file {path}: {e}")
        return ""


def parse_vivado_failure(raw_output: str):
    """Extracts a compact error summary from Vivado/XSim output."""
    if "not recognized" in raw_output:
        return "SYSTEM ERROR: Vivado path incorrect.", "System/Path Error"

    error_lines = []
    for line in raw_output.split("\n"):
        line_lower = line.lower()

        # Real Vivado/SystemVerilog errors
        if (
            "ERROR:" in line
            or "FATAL:" in line
            or "syntax error" in line_lower
            or "elaboration failed" in line_lower
            or "compilation failed" in line_lower
        ):
            error_lines.append(line)
            continue

        # UVM errors only if count > 0
        m_err = re.search(r"UVM_ERROR\s*:\s*(\d+)", line)
        if m_err and int(m_err.group(1)) > 0:
            error_lines.append(line)
            continue

        m_fat = re.search(r"UVM_FATAL\s*:\s*(\d+)", line)
        if m_fat and int(m_fat.group(1)) > 0:
            error_lines.append(line)
            continue

    if error_lines:
        errors = "\n".join(error_lines[:20])
    else:
        errors = (
            "Vivado/XSim returned a failure status, but no explicit blocking "
            "ERROR, FATAL, UVM_ERROR > 0, or UVM_FATAL > 0 was found."
        )

    return errors, "Vivado Execution Error"


def extract_relevant_error_lines(text: str, max_lines: int = 30) -> str:
    """Extracts the most relevant lines from Vivado/XSim/UVM logs."""
    if not text:
        return ""

    markers = [
        "ERROR:",
        "FATAL:",
        "CRITICAL WARNING:",
        "UVM_ERROR",
        "UVM_FATAL",
        "syntax error",
        "Syntax error",
        "FAILED",
        "failed",
        "xvlog",
        "xelab",
        "xsim",
    ]

    lines = text.splitlines()
    selected = []

    for i, line in enumerate(lines):
        if any(marker in line for marker in markers):
            start = max(0, i - 2)
            end = min(len(lines), i + 3)
            selected.extend(lines[start:end])

    # remove duplicates, keep order
    clean = []
    seen = set()

    for line in selected:
        if line not in seen:
            clean.append(line)
            seen.add(line)

    if clean:
        return "\n".join(clean[:max_lines])

    non_empty = [line for line in lines if line.strip()]
    return "\n".join(non_empty[-max_lines:])


def classify_vivado_error(error_text: str) -> dict:
    """Classifies the error into a small number of categories."""
    text = (error_text or "").lower()

    if "not recognized" in text or "settings64.bat" in text or "vivado path" in text:
        return {
            "category": "SYSTEM_PATH_ERROR",
            "auto_fix_allowed": False,
            "recommendation": (
                "This looks like an environment problem. Check the Vivado path, "
                "settings64.bat, and whether xvlog/xelab/xsim are available."
            ),
        }

    if "coverage report" in text or "xcrg" in text or "coverage report missing" in text:
        return {
            "category": "COVERAGE_REPORT_ERROR",
            "auto_fix_allowed": False,
            "recommendation": (
                "Vivado may have run, but the coverage report was not generated or "
                "could not be parsed. Check the xcrg command and coverage database path."
            ),
        }

    if "xvlog" in text or "syntax error" in text or "near" in text:
        return {
            "category": "COMPILE_SYNTAX_ERROR",
            "auto_fix_allowed": True,
            "recommendation": (
                "The injected SystemVerilog/UVM code likely contains a syntax error "
                "or an invalid declaration. The generated code should be corrected."
            ),
        }

    if "xelab" in text:
        return {
            "category": "ELABORATION_ERROR",
            "auto_fix_allowed": True,
            "recommendation": (
                "The code compiled, but elaboration failed. Check class names, "
                "factory registration, include order, top module, and UVM test names."
            ),
        }

    uvm_error_match = re.search(r"UVM_ERROR\s*:\s*(\d+)", error_text or "")
    uvm_fatal_match = re.search(r"UVM_FATAL\s*:\s*(\d+)", error_text or "")

    uvm_error_count = int(uvm_error_match.group(1)) if uvm_error_match else 0
    uvm_fatal_count = int(uvm_fatal_match.group(1)) if uvm_fatal_match else 0

    if (uvm_error_count > 0 or uvm_fatal_count > 0 or "mismatch" in text):
        return {
            "category": "SIMULATION_RUNTIME_ERROR",
            "auto_fix_allowed": True,
            "recommendation": (
                "The simulation ran but reported a UVM/runtime failure. Check the "
                "generated sequence/test behavior and scoreboard expectations."
                ),
        }

    return {
        "category": "UNKNOWN_VIVADO_ERROR",
        "auto_fix_allowed": True,
        "recommendation": (
            "The error could not be classified safely. Review the relevant Vivado/XSim "
            "log lines and regenerate only a minimal fix."
        ),
    }


def guess_target_files_from_error(error_text: str, state: AgentState) -> str:
    """
    Guesses likely affected files using:
    - current target_file from previous plan;
    - // FILE markers from generated code;
    - file names mentioned in the error.
    """
    known_files = [
        "transaction.sv",
        "sequence.sv",
        "test.sv",
        "subscriber.sv",
        "monitor.sv",
        "driver.sv",
        "scoreboard.sv",
        "agent.sv",
        "environment.sv",
        "top.sv",
        "MakeSVfile.bat",
    ]

    text = (error_text or "").lower()
    generated_code = state.get("generated_code", "")
    current_target = state.get("target_file", "")

    candidates = []

    if current_target and "unknown" not in current_target.lower():
        candidates.extend([f.strip() for f in current_target.split(",") if f.strip()])

    for match in re.finditer(r"FILE:\s*([a-zA-Z0-9_.-]+)", generated_code):
        candidates.append(match.group(1).strip())

    for file_name in known_files:
        if file_name.lower() in text:
            candidates.append(file_name)

    candidates = list(dict.fromkeys(candidates))

    if candidates:
        return ", ".join(candidates)

    return "sequence.sv, test.sv, subscriber.sv, MakeSVfile.bat"


def build_error_fix_plan(category: str,target_files: str,recommendation: str,evidence: str) -> str:
    """Builds a recovery plan after a Vivado/XSim failure."""

    return (
        "SHORT_RESPONSE:\n"
        "Vivado/XSim reported an error after the last run. The system should not "
        "continue coverage comparison until this error is fixed.\n\n"

        "ROOT_CAUSE_SUMMARY:\n"
        f"Error category: {category}.\n"
        f"{recommendation}\n\n"

        "CHOSEN STRATEGY: TESTBENCH_WIRING_FIX\n"
        "CODE_ACTION: MODIFY\n"
        f"TARGET_FILES: {target_files}\n\n"

        "PLANNED_CHANGE:\n"
        "Generate the smallest correction needed to make the modified verification "
        "environment compile and run again. The fix must target only the files related "
        "to the last generated code or run script change.\n\n"

        "EVIDENCE:\n"
        f"{evidence[:2000]}"
    )

